# Goal - I have to ensure the packages and dependencies have been audited for security

name: dependency scan

on: 
    workflow_call:

jobs: 
    dependency-scan:
       runs-on: ubuntu-latest
       steps: 
          - name: code checkout
            uses: actions/checkout@v7

          - name: Setup Go
            uses: actions/setup-go@v4
            with:  
                go-version: 1.25
                go-version-file: 'go.mod'
                cache-dependency-path: go.sum

          - name: Install Govulncheck
            run: go install golang.org/x/vuln/cmd/govulncheck@1.1.4      

          - name: GoVulncheck  
            continue-on-error: true
            run: govulncheck ./... > govulncheck-report.txt
            working directory: backend

          - name: Setup Node
            uses: actions/setup-node@v6
            with:  
                node-version: '20'
                cache: npm
                cache-dependency-path: frontend/package-lock.json

          - name: Run Dependency Scan for Node
            run: npm audited
            working directory: frontend

          - name: Upload Report to Artifacts
            if: always() #Ensure report uploaads even if tests fail
            uses: actions/upload-atrifact@v4
            with: 
                name: dependency-scan-report
                path: reports/dependency-report.txt
                retention-days: 5 