# Goal -  To run the end to end DevSecOps pipeline

name: DevSecOps

on:
  push:
      branches: [master]
jobs:
  # Code Stage (with shift left) 
  code-quality:
      uses: ./.github/workflows/code-quality.yml

  # Secret Scanning
  secret-scanning:
       uses: ./.github/workflows/secret-scanning.yml

  # Dependency Checks
  dependency-Checks:
        uses: ./.github/workflows/dependency-scan.yml

  # Docker Checks
  docker-Checks:
        uses: ./.github/workflows/docker-scans.yml     
        secrets: inherit

  # SonarQube     
  sonar_qube:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit

  # Code Tests
  code-test: 
        uses: ./.github/worflows/code-test.yml

  # push-to-docker-hub 
  docker-push:
      needs: [code-quality,code-test,secret-scanning,dependency-Checks,docker-Checks,sonar_qube]
      uses: ./.github/worflows/docker-push.yml
      secrets: inherit